### ISSUE TITLE
Can't update descriptor for a past due subscription

### ISSUE THREAD

**Issue by therool** [braintree/braintree_php#110] opened 2015-11-11 13:28 UTC
When I try to update descriptor for a past due subscription the reponse returns error: **91920** but the same code works fine for active subscriptions. https://developers.braintreepayments.com/reference/general/validation-errors/all/php#subscription
```php
$subscriptions = \Braintree_Subscription::search([
	\Braintree_SubscriptionSearch::status()->in(array(
        \Braintree_Subscription::PAST_DUE,
    ))
]);

foreach ( $subscriptions as $subscription ) {
	$response = \Braintree_Subscription::update( $subscription->id, [
		'descriptor' => [
			'name'    => null,
			'phone'   => null,
			'url'     => null
		]
	]);

	if ( ! $response->success ) {
		pr($response);die;
	}
}
```

**Comment by kexline4710** [comment] 2015-11-30 20:07
@therool, thank you for bringing this to our attention! The issue appears to be internal and unrelated to the PHP library. We are working on a fix and will release it as soon as we can. I will be sure to inform you on here as soon as the issue is resolved.

**Comment by kexline4710** [comment] 2015-12-11 17:54
Hi @therool! Just wanted to follow up and let you know that we've deployed a fix for this. You should no longer encounter any issues when updating descriptor fields for a past due subscription.

**Closed by kexline4710** 2015-12-11 17:54 UTC
