### ISSUE TITLE
Insufficient info in Authorization errors

### ISSUE THREAD

**Issue by Synchro** [braintree/braintree_php#308] opened 2021-12-06 23:46 UTC
### General information

* SDK/Library version: 6.5.0
* Environment: Sandbox
* Language, language version, and OS: PHP 8.0 on Ubuntu 20.04

### Issue description

I have an integration issue, but I could not track down the cause because the SDK omits critical information.

Sample code:
```php
$gateway = new Braintree\Gateway(
      [
          'environment' => config('payments.braintree.env'),
          'merchantId'  => config('payments.braintree.merchant_id'),
          'publicKey'   => config('payments.braintree.public_key'),
          'privateKey'  => config('payments.braintree.private_key'),
      ]
);
$customer = $gateway->customer()->find('<valid customer ID>');
// dump($customer);
$params = [
    "amount" => "8.4",
    "customerId" => "<valid customer ID>",
    "merchantAccountId" => "<account ID>",
    "options" => ["submitForSettlement" => true]
  ];

try{
    $result = $gateway->transaction()->sale($params);
} catch (Exception $e) {
    dump($e);
}
```

I was certain that  that the credentials were correct because the call to `customer->find()` worked, but this code throws an Authorization exception, which is exceedingly unhelpful:

```
Braintree\Exception\Authorization {#2363
  #message: ""
  #code: 0
  #file: "vendor/braintree/braintree_php/lib/Braintree/Util.php"
  #line: 63
```

Note that it contains no contextual information at all. So I spent a long time trying to figure out what was wrong, mainly (since this was Authorization, after all) looking at roles and permissions. Eventually it occurred to me that I should check **all** my inputs, so I called:

    $merchantAccount = $gateway->merchantAccount()->find('<account ID>');

Which gave me the enormously helpful:

> Braintree/Exception/NotFound with message 'merchant account with id <account id> not found'

So my request here is to have that exception thrown (or at least some contextual info to hint at the cause) in the exception thrown from sale. I'd say the right way to do this is to throw the existing `Braintree\Exception\Authorization` exception, but include the previous `Braintree\Exception\NotFound` exception inside it so you don't break BC, but can get at the extra info by calling `getPrevious()` on the outer exception – which is not currently being used.

**Comment by TiaNex-Com** [comment] 2022-08-11 05:05
yes, after i deleted the default api keys in my sandbox account,
i always got the "Braintree\Exception\Authentication" 401 error.

**Comment by hollabaq86** [comment] 2022-10-03 21:46
👋 @synchro, thanks for reaching out. I'm going to forward this feedback to the engineering team that determines authorization for review. This definitely presents a scenario where the SDK is surfacing an Authorization error but the underlying issue (merchant account) isn't getting surfaced in the error response for the SDK to [surface](https://github.com/braintree/braintree_php/blob/e7f0b691e6b0b39bf5dad703d955d0318a67c367/lib/Braintree/Util.php#L62).

Since the underlying root of the issue is on the API response and not the SDK itself, I'm going to go ahead and close this.

**Closed by hollabaq86** 2022-10-03 21:46 UTC
