### ISSUE TITLE
Code like it is 2015

### ISSUE THREAD

**Issue by bazo** [braintree/braintree_php#111] opened 2015-11-12 15:31 UTC
Hi,

we are using your php api in our app and I as the developer am very unsatisfied with the experience

the problem is that we love to use modern practices such as namespaces and dependency injection.

so i built a thin wrapper on top of your api which lets me configure braintree in config and then autowire it where necessary

until now we were using one instance of braintree

but now the situation changed and we have the need to use multiple merchantIds so i built a factory for braintree that the return a correct instance of my Braintree wrapper class with corresponding configuration

the factory is now used instead of the staticly configured one instance of wrapper, so the calls to create braintree are dynamic all over the code

but still the underlying code of your api static calls, singletons, etc which is quite a mess
i guess such use of static classes and methods became deprecated in php community like 10 years ago

so please can you enhance the api to use namespaces and reduce the of static classes and calls in favor of using nice objects and dependency injection and modern practices of 2015?

thank you very much for any reply

**Comment by matthewpatterson** [comment] 2015-11-12 20:12
Hi @bazo,

I'm a developer here at Braintree and I understand that you are trying to use the Braintree PHP library with multiple merchant credentials.

This is a use case we don't come across often since it is possible to have multiple merchant accounts within a given merchant ID and public/private key combination. As such, it's not covered very well in our documentation. However, it is indeed possible.

I've put together an example of how to use multiple sets of merchant credentials without using or modifying the global `Braintree\Configuration` instance. The example only covers a simple transaction sale, but the principles apply to any API call: anywhere you would use a static call, e.g. `Braintree\Transaction::sale()`, you can invoke the same method off of the correct Gateway object: `$gateway->transaction()->sale()` (given `$gateway` is an instance of `Braintree\Gateway`).

You can find the full example here: https://github.com/matthewpatterson/braintree_multi_merchant_example

With respect to your suggest about using namespaces, I have good news! We implemented namespaces in [v3.6.1](https://github.com/braintree/braintree_php/releases/tag/3.6.1). All classes in the Braintree PHP library now follow PSR-4 naming conventions and can be autoloaded using any PSR-0 or PSR-4 compatible autoloader. We plan to completely remove the non-namespaced classes in v4.0, and between now and then we will be updating all of our documentation to reflect the new, namespaced class names.

I hope this helps! I'm going to close this issue for now, but if you have any issues using the approach shown in my example, feel free to reach out to support@braintreepayments.com.

-mattpatt

**Closed by matthewpatterson** 2015-11-12 20:12 UTC

**Comment by githoober** [comment] 2015-12-07 05:28
If would be also nice to see a comment on another problem mentioned in this issue, that is the amount of static code. Are there any plans to remove it in future?

**Comment by matthewpatterson** [comment] 2015-12-07 18:49
Hi @githoober,

Actually, most of our static code is a facade for instance method calls against the globally configured Gateway, like this example from the `Braintree\Transaction` class:

```php
public static function sale($attribs)
{
    return Configuration::gateway()->transaction()->sale($attribs);
}
```

Our goal here is to expose an API that is simple to use, rather than requiring developers to have knowledge about the internals of our library. Of course, you can work around these APIs if you have other needs, such as creating transactions for multiple merchants.

At this time, we have no plans to remove any static methods in the code base.

-mattpatt

**Comment by githoober** [comment] 2016-01-05 21:55
@matthewpatterson the problem is the working around your dynamic APIs that are not documented may create a problem in future when you decide to change APIs.

**Comment by matthewpatterson** [comment] 2016-01-06 19:15
@githoober I'll pass this feedback along to our documentation team to see if it can be added. If you are worried about the API changing, I would suggest locking to a specific version number in your `composer.json` file.
